export { default as clothesImage } from "./DreamShaper_v7_funky_modern_design_for_a_human_wearing_clothes_1-min.jpg";
export { default as accessoriesImage } from "./DreamShaper_v7_vibrant_modern_design_for_accessories_1-min.jpg";
export { default as accessoriesHero } from "./accessories.jpg";
export { default as giftHero } from "./gift hero.jpg";
export { default as clothesHero } from "./clothes.jpg";
export { default as hatSubCategory } from "./hat.jpg";
export { default as socksSubCategory } from "./socks.jpg";
export { default as hoodieSubCategory } from "./hoodie.jpg";
export { default as skirtSubCategory } from "./skirt.jpg";
export { default as necklaseSubCategory } from "./necklase.jpg";
export { default as braceleteSubCategory } from "./bracelete.jpg";
export { default as headbandSubCategory } from "./headband.jpg";
export { default as totebagSubCategory } from "./tote bag.jpeg";
export { default as hairSubCategory } from "./hair.jpg";
export { default as skincareSubCategory } from "./skincare.jpg";
export { default as bagSubCategory } from "./bag.jpg";
export { default as sportswearCategory } from "./sportsWearMain.jpg";
export { default as sportsweaSubCategory } from "./sportswearHero.jpg";
export { default as sportsweaCroptTopCategory } from "./sportsWearCropTop.jpg";
export { default as sportsweaJoggerCategory } from "./sportsWearJoggers.jpg";
export { default as sportsweaLeggingsCategory } from "./sportsWearLeggings.jpg";
export { default as sportsweaSportingBraCategory } from "./sportsWearSportingBra.jpg";
export { default as giftLipCategory } from "./ipstick.jpg";
